export const projects = [
  {
    id: "16",
    name: "GabySystem",
    type: "Web Application",
    technology: "NODEJS - REACT",
    technologies: ["HTML", "CSS", "JAVASCRIPT", "REACT", "NODEJS", "BOOTSTRAP"],
    urlGithub: "https://github.com/gabyreload1983/api-gabysystem",
    urlDeploy: "",
    urlImage:
      "https://gabrielgodoy.com.ar/resources/images/projects/gabysystem.png",
  },
  {
    id: "15",
    name: "Helpdesk Tickets",
    type: "Web Application",
    technology: "NEXTJS",
    technologies: ["HTML", "CSS", "JAVASCRIPT", "REACT", "NEXTJS", "TAILWIND"],
    urlGithub: "https://github.com/gabyreload1983/netninja-next-tutorial",
    urlDeploy: "https://netninja-next-tutorial.vercel.app/",
    urlImage:
      "https://gabrielgodoy.com.ar/resources/images/projects/helpdesk-nextjs.png",
  },
  {
    id: "14",
    name: "Van Life",
    type: "Web Application",
    technology: "REACT",
    technologies: ["HTML", "CSS", "JAVASCRIPT", "REACT"],
    urlGithub: "https://github.com/gabyreload1983/van-life",
    urlDeploy: "https://gabyreload-van-life.netlify.app/",
    urlImage:
      "https://gabrielgodoy.com.ar/resources/images/projects/van-life.png",
  },
  {
    id: "13",
    name: "Password Generator",
    type: "Web Application",
    technology: "JAVASCRIPT",
    technologies: ["HTML", "CSS", "JAVASCRIPT"],
    urlGithub: "https://github.com/gabyreload1983/password-generator-js",
    urlDeploy: "https://password-generator-js-lilac.vercel.app/",
    urlImage:
      "https://gabrielgodoy.com.ar/resources/images/projects/passwordGenerator.png",
  },
  {
    id: "12",
    name: "Chat Websocket",
    type: "Web Application",
    technology: "WEBSOCKET",
    technologies: [
      "HTML",
      "CSS",
      "JAVASCRIPT",
      "BOOTSTRAP",
      "NODEJS",
      "WEBSOCKET",
    ],
    urlGithub: "https://github.com/gabyreload1983/chatWebsocket",
    urlDeploy: "https://daisy-secretive-eggnog.glitch.me/",
    urlImage:
      "https://gabrielgodoy.com.ar/resources/images/projects/websocket.png",
  },
  {
    id: "11",
    name: "CoderHouse Reactjs",
    type: "Web Application",
    technology: "REACTJS",
    technologies: ["HTML", "CSS", "JAVASCRIPT", "BOOTSTRAP", "REACTJS"],
    urlGithub: "https://github.com/gabyreload1983/coderHouseReact-GabrielGodoy",
    urlDeploy: "https://coder-house-react-gabriel-godoy.vercel.app/",
    urlImage:
      "https://gabrielgodoy.com.ar/resources/images/projects/coderReactjs.png",
  },
  {
    id: "10",
    name: "CoderHouse Javascript",
    type: "Web Application",
    technology: "JAVASCRIPT",
    technologies: ["HTML", "CSS", "JAVASCRIPT", "BOOTSTRAP"],
    urlGithub: "https://github.com/gabyreload1983/coderHouseJavascript",
    urlDeploy: "https://gabyreload1983.github.io/coderHouseJavascript/",
    urlImage:
      "https://gabrielgodoy.com.ar/resources/images/projects/coderJavascript.png",
  },
  {
    id: "9",
    name: "Tic Tac Toe",
    type: "Web Application",
    technology: "REACTJS",
    technologies: ["HTML", "CSS", "JAVASCRIPT", "BOOTSTRAP", "REACT"],
    urlGithub: "https://github.com/gabyreload1983/tic-tac-toe",
    urlDeploy: "https://tic-tac-toe-ashen-beta.vercel.app/",
    urlImage:
      "https://gabrielgodoy.com.ar/resources/images/projects/tictactoe.png",
  },
  {
    id: "8",
    name: "Meme Generator",
    type: "Web Application",
    technology: "REACTJS",
    technologies: ["HTML", "CSS", "JAVASCRIPT", "BOOTSTRAP", "REACT"],
    urlGithub: "https://github.com/gabyreload1983/meme-generator-react",
    urlDeploy: "https://meme-generator-react-rosy.vercel.app/",
    urlImage:
      "https://gabrielgodoy.com.ar/resources/images/projects/memeGenerator.png",
  },
  {
    id: "7",
    name: "Vidly",
    type: "Web Application",
    technology: "REACTJS",
    technologies: ["HTML", "CSS", "JAVASCRIPT", "BOOTSTRAP", "REACT"],
    urlGithub: "https://github.com/gabyreload1983/vidly-frontend",
    urlDeploy: "https://vidly-frontend.vercel.app/movies",
    urlImage: "https://gabrielgodoy.com.ar/resources/images/projects/vidly.png",
  },
  {
    id: "6",
    name: "Tenzies",
    type: "Web Application Game",
    technology: "REACTJS",
    technologies: ["HTML", "CSS", "JAVASCRIPT", "BOOTSTRAP", "REACT"],
    urlGithub: "https://github.com/gabyreload1983/React-dices-game",
    urlDeploy: "https://gabyreload-tenzie.netlify.app/",
    urlImage:
      "https://gabrielgodoy.com.ar/resources/images/projects/tenzies.png",
  },
  {
    id: "5",
    name: "Login",
    type: "Web Application",
    technology: "NODEJS",
    technologies: [
      "HTML",
      "CSS",
      "JAVASCRIPT",
      "BOOTSTRAP",
      "NODEJS",
      "EXPRESS",
      "MONGODB",
    ],
    urlGithub: "https://github.com/gabyreload1983/NodeJs-Login",
    urlDeploy: "https://gabyreload-nodejs-login.herokuapp.com/",
    urlImage: "https://gabrielgodoy.com.ar/resources/images/projects/login.png",
  },
  {
    id: "4",
    name: "Notes Blog",
    type: "Web Application",
    technology: "NODEJS",
    technologies: ["HTML", "CSS", "JAVASCRIPT", "NODEJS", "EXPRESS", "MONGODB"],
    urlGithub: "https://github.com/gabyreload1983/NodeJs-Notas",
    urlDeploy: "https://reloadnotes.herokuapp.com/",
    urlImage: "https://gabrielgodoy.com.ar/resources/images/projects/notes.png",
  },
  {
    id: "3",
    name: "Sinapsis App",
    type: "Web Application",
    technology: "NODEJS",
    technologies: [
      "HTML",
      "CSS",
      "JAVASCRIPT",
      "BOOTSTRAP",
      "NODEJS",
      "EXPRESS",
      "MONGODB",
      "MYSQL",
    ],
    urlGithub: "https://github.com/gabyreload1983/app-sinapsis",
    urlDeploy: "",
    urlImage:
      "https://gabrielgodoy.com.ar/resources/images/projects/sinapsis.png",
  },
  {
    id: "2",
    name: "Moshify",
    type: "Web Page",
    technology: "HTML",
    technologies: ["HTML", "CSS", "BOOTSTRAP"],
    urlGithub: "https://github.com/gabyreload1983/Moshify",
    urlDeploy: "https://proyectomosh.netlify.app/",
    urlImage:
      "https://gabrielgodoy.com.ar/resources/images/projects/moshify.png",
  },
  {
    id: "1",
    name: "Estudio Contable Mugica",
    type: "Web Page",
    technology: "HTML",
    technologies: ["HTML", "CSS", "JAVASCRIPT", "BOOTSTRAP", "JAVASCRIPT"],
    urlGithub: "https://github.com/gabyreload1983/Estudio-Contable-Mugica",
    urlDeploy: "https://estudio-contable-mugica.vercel.app/",
    urlImage:
      "https://gabrielgodoy.com.ar/resources/images/projects/estudio.png",
  },
];

export const aboutGallery = [
  {
    id: "1",
    width: 1280,
    height: 960,
    url: "https://gabrielgodoy.com.ar/resources/images/about/about-01.jpg",
    alt: "",
  },
  {
    id: "2",
    width: 1200,
    height: 1600,
    url: "https://gabrielgodoy.com.ar/resources/images/about/about-02.jpg",
    alt: "",
  },
  {
    id: "3",
    width: 4032,
    height: 3024,
    url: "https://gabrielgodoy.com.ar/resources/images/about/about-03.jpg",
    alt: "",
  },
  {
    id: "4",
    width: 3648,
    height: 2736,
    url: "https://gabrielgodoy.com.ar/resources/images/about/about-04.jpg",
    alt: "",
  },
  {
    id: "5",
    width: 3000,
    height: 4000,
    url: "https://gabrielgodoy.com.ar/resources/images/about/about-05.jpg",
    alt: "",
  },
  {
    id: "6",
    width: 4000,
    height: 3000,
    url: "https://gabrielgodoy.com.ar/resources/images/about/about-06.jpg",
    alt: "",
  },
  {
    id: "7",
    width: 4000,
    height: 3000,
    url: "https://gabrielgodoy.com.ar/resources/images/about/about-07.jpg",
    alt: "",
  },
  {
    id: "8",
    width: 4000,
    height: 3000,
    url: "https://gabrielgodoy.com.ar/resources/images/about/about-08.jpg",
    alt: "",
  },
  {
    id: "9",
    width: 4000,
    height: 3000,
    url: "https://gabrielgodoy.com.ar/resources/images/about/about-09.jpg",
    alt: "",
  },
  {
    id: "10",
    width: 4000,
    height: 3000,
    url: "https://gabrielgodoy.com.ar/resources/images/about/about-10.jpg",
    alt: "",
  },
  {
    id: "11",
    width: 4000,
    height: 3000,
    url: "https://gabrielgodoy.com.ar/resources/images/about/about-11.jpg",
    alt: "",
  },
  {
    id: "12",
    width: 1600,
    height: 900,
    url: "https://gabrielgodoy.com.ar/resources/images/about/about-12.jpg",
    alt: "",
  },
  {
    id: "13",
    width: 1920,
    height: 1080,
    url: "https://gabrielgodoy.com.ar/resources/images/about/about-13.jpg",
    alt: "",
  },
  {
    id: "14",
    width: 4608,
    height: 3456,
    url: "https://gabrielgodoy.com.ar/resources/images/about/about-14.jpg",
    alt: "",
  },
  {
    id: "15",
    width: 960,
    height: 1280,
    url: "https://gabrielgodoy.com.ar/resources/images/about/about-15.jpg",
    alt: "",
  },
];
